version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: param_adventures_db
    ports:
      # Host:Container â€” changed host port to 5433 to avoid conflicts with local Postgres
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: param_adventures
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
